export default [
  {title: 'Baby Driver', year: '2017', categoryid: 'action', imgURL: 'http://wwwcdn.howdesign.com/wp-content/uploads/7f2c6056de513cac.png', rating: '7.8  /  10', synopsis: 'After being coerced into working for a crime boss, a young getaway driver finds himself taking part in a heist doomed to fail.'},
  {title: 'Jaws', year: '1975', categoryid: 'adventure', imgURL: 'https://thelogocompany.net/wp-content/uploads/2017/05/Jaws-Poster.jpg', rating: '8.0  /  10', synopsis: 'A local sheriff, a marine biologist and an old seafarer team up to hunt down a great white shark wrecking havoc in a beach resort.'},
  {title: 'The Lost Boys', year: '1987', categoryid: 'comedy', imgURL: 'https://image.tmdb.org/t/p/original/uFgjP8QQlACPNuu3BLDusMnUkS8.jpg', rating: '7.3  /  10', synopsis: 'After moving to a new town, two brothers discover that the area is a haven for vampires.'},
  {title: 'Paterson', year: '2016', categoryid: 'comedy', imgURL: 'https://i.pinimg.com/originals/b4/41/ab/b441ab6dcf5f173003ffd55967aad6a3.jpg', rating: '7.4  /  10', synopsis: 'A quiet observation of the triumphs and defeats of daily life, along with the poetry evident in its smallest details.'},
  {title: 'Aliens', year: '1986', categoryid: 'action', imgURL: 'https://i.pinimg.com/originals/f2/91/c8/f291c8050011db1fa81c15b7a47f240c.jpg', rating: '8.4  /  10', synopsis: '57 years later, Ellen Ripley is rescued by a deep salvage team during her hypersleep. The moon from the original movie has been colonized, but contact is lost. This time, colonial marines have impressive firepower, but will that be enough?'},
  {title: 'Doctor Strange', year: '2016', categoryid: 'action', imgURL: 'https://i.pinimg.com/originals/06/f3/cc/06f3cce9b75a86291b52ca7a6f5a0d5d.jpg', rating: '7.5  /  10', synopsis: 'While on a journey of physical and spiritual healing, a brilliant neurosurgeon is drawn into the world of the mystic arts.'},
  {title: 'The Purge: Election Year', year: '2016', categoryid: 'action', imgURL: 'https://i.pinimg.com/originals/92/f7/04/92f7049b06be13ae2c45e9be15a57cd2.jpg', rating: '6.0  /  10', synopsis: 'Former Police Sergeant Barnes becomes head of security for Senator Charlie Roan, a Presidential candidate targeted for death on Purge night due to her vow to eliminate the Purge.'},
  {title: 'Blade Runner', year: '1982', categoryid: 'sci-fi', imgURL: 'http://barkerhost.com/wp-content/uploads/sites/4/2016/02/5ig0kdWz5kxR4PHjyCgyI5khCzd-1.jpg', rating: '8.2  /  10', synopsis: 'A blade runner must pursue and try to terminate four replicants who stole a ship in space and have returned to Earth to find their creator.'},
  {title: 'The Game Plan', year: '2007', categoryid: 'comedy', imgURL: 'https://i.pinimg.com/originals/6d/be/45/6dbe45e9b217b1b54c20531fe62c468a.jpg', rating: '6.2  /  10', synopsis: 'An NFL quarterback living the bachelor lifestyle discovers that he has an 8-year-old daughter from a previous relationship.'},
  {title: 'The Incredibles', year: '2004', categoryid: 'animation', imgURL: 'https://i.pinimg.com/originals/17/f6/ae/17f6aeb214940eaadf5754f19729d80d.jpg', rating: '8.0  /  10', synopsis: 'A family of undercover superheroes, while trying to live the quiet suburban life, are forced into action to save the world.'},
  {title: 'Missing in Action 2: The Beginning', year: '1985', categoryid: 'action', imgURL: 'http://mitocadorcoreano.com/wp-content/uploads/2017/11/collection-of-solutions-missing-in-action-2-the-beginning-1985-posters-%E2%80%94-the-movie-for-missing-in-action-poster-of-missing-in-action-poster.jpg', rating: '5.2/10', synopsis: 'Prequel to the first Missing In Action, set in the early 1980s it shows the capture of Colonel Braddock during the Vietnam war in the 1970s, and his captivity with other American POWs in a brutal prison camp, and his plans to escape.'}
]

/*
movie info template:
{title: '', year: '', categoryid: '', imgURL: '', rating: '', synopsis: ''},
*/
